// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourApp.Context;

namespace TourApp.Migrations
{
    [DbContext(typeof(TourContext))]
    partial class TourContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TourApp.Entity.CTChitieu", b =>
                {
                    b.Property<int>("CTId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TienCT")
                        .HasColumnType("INTEGER");

                    b.HasKey("CTId", "DoanId");

                    b.HasIndex("DoanId");

                    b.ToTable("CTChiTieus");
                });

            modelBuilder.Entity("TourApp.Entity.CTDoan", b =>
                {
                    b.Property<int>("DoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KhachId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoanId", "KhachId");

                    b.HasIndex("KhachId");

                    b.ToTable("CTDoans");
                });

            modelBuilder.Entity("TourApp.Entity.CTTour", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DDId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThongTin")
                        .HasColumnType("TEXT");

                    b.HasKey("TourId", "DDId");

                    b.HasIndex("DDId");

                    b.ToTable("CTTours");
                });

            modelBuilder.Entity("TourApp.Entity.ChiTieu", b =>
                {
                    b.Property<int>("CTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.HasKey("CTId");

                    b.ToTable("ChiTieus");
                });

            modelBuilder.Entity("TourApp.Entity.DiaDiem", b =>
                {
                    b.Property<int>("DDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaDD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DDId");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("TourApp.Entity.DoanKhach", b =>
                {
                    b.Property<int>("DoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chitiet")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDoan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDoan")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoanId");

                    b.HasIndex("TourId");

                    b.ToTable("DoanKhachs");
                });

            modelBuilder.Entity("TourApp.Entity.Gia", b =>
                {
                    b.Property<int>("GiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiaTri")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaGia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TGBD")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TGKT")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GiaId");

                    b.HasIndex("TourId");

                    b.ToTable("Gias");
                });

            modelBuilder.Entity("TourApp.Entity.HanhKhach", b =>
                {
                    b.Property<int>("KhachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhach")
                        .HasColumnType("TEXT");

                    b.Property<int>("SDT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.HasKey("KhachId");

                    b.ToTable("HanhKhachs");
                });

            modelBuilder.Entity("TourApp.Entity.NV_VT", b =>
                {
                    b.Property<int>("DoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NVId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViTri")
                        .HasColumnType("TEXT");

                    b.HasKey("DoanId", "NVId");

                    b.HasIndex("NVId");

                    b.ToTable("NV_VTs");
                });

            modelBuilder.Entity("TourApp.Entity.NhanVien", b =>
                {
                    b.Property<int>("NVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaNV")
                        .HasColumnType("TEXT");

                    b.Property<string>("SDT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.HasKey("NVId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("TourApp.Entity.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaTour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourApp.Entity.CTChitieu", b =>
                {
                    b.HasOne("TourApp.Entity.ChiTieu", "ChiTieu")
                        .WithMany("CTChitieus")
                        .HasForeignKey("CTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourApp.Entity.DoanKhach", "DoanKhach")
                        .WithMany("CTChitieus")
                        .HasForeignKey("DoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourApp.Entity.CTDoan", b =>
                {
                    b.HasOne("TourApp.Entity.DoanKhach", "DoanKhach")
                        .WithMany("CTDoans")
                        .HasForeignKey("DoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourApp.Entity.HanhKhach", "HanhKhach")
                        .WithMany("CTDoans")
                        .HasForeignKey("KhachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourApp.Entity.CTTour", b =>
                {
                    b.HasOne("TourApp.Entity.DiaDiem", "DiaDiem")
                        .WithMany("CTTours")
                        .HasForeignKey("DDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourApp.Entity.Tour", "Tour")
                        .WithMany("CTTours")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourApp.Entity.DoanKhach", b =>
                {
                    b.HasOne("TourApp.Entity.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourApp.Entity.Gia", b =>
                {
                    b.HasOne("TourApp.Entity.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourApp.Entity.NV_VT", b =>
                {
                    b.HasOne("TourApp.Entity.DoanKhach", "DoanKhach")
                        .WithMany("NV_VTs")
                        .HasForeignKey("DoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourApp.Entity.NhanVien", "NhanVien")
                        .WithMany("NV_VTs")
                        .HasForeignKey("NVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
